### ISSUE TITLE
Error when sorting by Overdue Interval

### ISSUE THREAD

**Issue by GabbriOunon** [ankipalace/advanced-browser#112]
When I try to select/sort in browser by Overdue interval I get this message 
"DBError {info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near\\\"select\\\": syntax error\"))", kind: Other} "
The only workouround for me seems to be reinstalling
Thank you

**Comment by honis56** [comment]
Same problem.

**Comment by yar00001** [comment]
Same problem as well.

**Comment by brainexcerpts** [comment]
Same here.

-----------------------------

Anki Desktop 2.1.44
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
UI language set to Japanese

In the browser clicking on the "Overdue Interval" tab will trigger the following pop up error and make the cards disappear in the browser.

DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near \\\"select\\\": syntax error\"))", kind: Other }

Other subsequent browsing related action will then keep trigger the error and cards won't show up.
However as soon as you click on another sorting option the cards appear again and the error stops popping up.

**Comment by ijgnd** [comment]
still occuris in 2.1.50beta

**Comment by 425833137** [comment]
same problem in 2.1.49 (dc80804a)⁩

**Comment by ijgnd** [comment]
for details see #148 and #149 .

This bug seems to have occured since Anki 2.1.24 up to 2.1.54 (2022-09). It's always fixed by abdnh's commit #144.
