### ISSUE TITLE
It doesn't't work on MacBook!

### ISSUE THREAD

**Issue by prusrafal** [ankipalace/advanced-browser#115]
I disabled all other add-ons etc. Doesn't work!!!

**Comment by hssm** [comment]
This doesn't tell me anything

**Comment by prusrafal** [comment]
This add-on doesn't work. What can I say more?

**Comment by andrewcrook** [comment]
@prusrafal 

> This add-on doesn't work. What can I say more?

How is it failing?
what versions of Anki, python, qt, and macOS  (is it on a M1?)
Are there any error messages from Anki? 
does it crash Anki?
or does it load?
any log information from Anki?
Does any of the functionality work?
