### ISSUE TITLE
Suggestion: Paste content only

### ISSUE THREAD

**Issue by honis56** [ankipalace/advanced-browser#124]
Hello,

would be nice if there was another menu item in

Browser -> right click on a field of a card -> 

----------
cut
copy
paste
***paste content only***
----------

to paste without formats.

With kind regards

**Comment by ijgnd** [comment]
you ask about an additional feature for the editor that you see at the bottom of the browser window whereas this add-on is only about the upper table.

Im not sure what you mean by "content only" but there are already add-ons like [paste plain/unformatted text](https://ankiweb.net/shared/info/107041104) and in Anki you have the shortcut ctrl+shift+v to paste without formatting (though this is not in the context menu).
