### ISSUE TITLE
Anki 2.1.35-40  Anki 2.1.24-27 and AB version from ankiweb from 2020-11-08: DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near \\\"select\\\": syntax error\"))", kind: Other }

### ISSUE THREAD

**Issue by ijgnd** [ankipalace/advanced-browser#149]
I just tested with Anki 2.1.**35** and 2.1.**40** and just the AB add-on that I downloaded from ankiweb today which is the version uploaded to ankiweb on 2020-**11-08**.

&nbsp;

This seems to be #112.

&nbsp;

I get a warning popup with the text

    DBError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"near \\\"select\\\": syntax error\"))", kind: Other }

in the console no error message is printed.

&nbsp;

That's the same behavior as in 2.1.28-2.1.34, see https://github.com/ankipalace/advanced-browser/issues/148#issue-1387630225

&nbsp;

**fix**: same as in #148: I would just backport abdo's patch: I would download the zip/ankiaddon file from ankiweb for the versions .35-.40, unzip it, manually change the [three lines that abdo changed](https://github.com/ankipalace/advanced-browser/pull/144/commits/fc03f5e6d1a7d7596961604774fb32416bd8f599), rezip it and upload it to ankiweb. To manually download it go to https://ankiweb.net/shared/download/874215009?v=2.1&p=35 in your browser.

**Comment by ijgnd** [comment]
@abdnh: 

same as #148 : if you have some time could you verify that this works? Since AB is so popular I think four eyes are better before it's released into the wild. Thanks.

**Comment by abdnh** [comment]
Works in 2.1.35
