### ISSUE TITLE
Can we change the variable name from  “Previous Duration time” to  “Last Review Time” 

### ISSUE THREAD

**Issue by sskpe500** [ankipalace/advanced-browser#27]
Thank you so much for adding the new variables in the Advanced Browser in Version 1.5.3.

Could the “Previous Duration time” name be changed to “Last Review Time” to be more consistent with the other variable names.

**Comment by hssm** [comment]
There is already a "Last Review" column which would make this confusing.

**Comment by ijgnd** [comment]
I agree with hssm, so I'm closing this.
