### ISSUE TITLE
Option to show tooltip when hovering over a cell

### ISSUE THREAD

**Issue by galantra** [ankipalace/advanced-browser#55]
Hi,
some of my information is too long to fit the column, e.g., hierarchical tags and decks. A tooltip that shows the full information would be great, preferably with an option to enable/disable it. I think this would be a remarkable improvement in everyday usage for many users.

**Comment by ijgnd** [comment]
tooltips for cells are built into Anki 2.1.49. I don't know when this was added. I guess we can close this issue. If not reopen it.
